import React, { useState, useEffect, useRef } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { CornerDownLeft, Globe, Mic, RotateCcw, Zap } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { useSocket } from "@/hooks/use-socket";
import { apiRequest } from "@/lib/queryClient";

interface CommentaryEntry {
  id: string;
  matchId: number;
  text: string;
  isAutoGenerated: boolean;
  type: 'wicket' | 'boundary' | 'milestone' | 'general' | 'strategic' | 'manual';
  timestamp: Date;
  over?: string;
  ball?: number;
  ballId?: number;
  playerId?: number;
  playerName?: string;
}

interface MatchCommentaryProps {
  matchId: number;
  currentInnings: number;
  autoGeneratedCommentary?: string;
  onSave?: (commentary: CommentaryEntry) => void;
}

export default function MatchCommentary({ 
  matchId, 
  currentInnings, 
  autoGeneratedCommentary,
  onSave
}: MatchCommentaryProps) {
  const [commentaryEntries, setCommentaryEntries] = useState<CommentaryEntry[]>([]);
  const [manualEntry, setManualEntry] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();
  const scrollRef = useRef<HTMLDivElement>(null);
  const socket = useSocket();

  useEffect(() => {
    // Load commentary history from API
    const loadCommentary = async () => {
      try {
        setIsLoading(true);
        const response = await apiRequest(`/api/matches/${matchId}/commentary`);
        if (response.ok) {
          const data = await response.json();
          setCommentaryEntries(data);
        }
      } catch (error) {
        console.error("Failed to load commentary:", error);
      } finally {
        setIsLoading(false);
      }
    };

    loadCommentary();

    // Set up socket connection for real-time updates
    if (socket) {
      socket.on(`match:${matchId}:commentary`, (newEntry: CommentaryEntry) => {
        setCommentaryEntries(prev => [newEntry, ...prev]);
      });
    }

    return () => {
      if (socket) {
        socket.off(`match:${matchId}:commentary`);
      }
    };
  }, [matchId, socket]);

  // Add auto-generated commentary when provided
  useEffect(() => {
    if (autoGeneratedCommentary) {
      const newEntry: CommentaryEntry = {
        id: `auto-${Date.now()}`,
        matchId,
        text: autoGeneratedCommentary,
        isAutoGenerated: true,
        type: 'general',
        timestamp: new Date()
      };
      
      setCommentaryEntries(prev => [newEntry, ...prev]);
      
      if (onSave) {
        onSave(newEntry);
      }
    }
  }, [autoGeneratedCommentary, matchId, onSave]);

  // Scroll to bottom when new entries are added
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = 0;
    }
  }, [commentaryEntries]);

  const handleAddManualCommentary = async () => {
    if (!manualEntry.trim()) return;

    try {
      setIsLoading(true);
      
      const newEntry: Omit<CommentaryEntry, 'id' | 'timestamp'> = {
        matchId,
        text: manualEntry,
        isAutoGenerated: false,
        type: 'manual'
      };
      
      const response = await apiRequest(`/api/matches/${matchId}/commentary`, {
        method: 'POST',
        body: JSON.stringify(newEntry)
      });
      
      if (response.ok) {
        const savedEntry = await response.json();
        setCommentaryEntries(prev => [savedEntry, ...prev]);
        setManualEntry("");
        
        toast({
          title: "Commentary Added",
          description: "Your commentary has been added to the match"
        });
      } else {
        throw new Error("Failed to save commentary");
      }
    } catch (error) {
      console.error("Error adding commentary:", error);
      toast({
        title: "Error",
        description: "Failed to add commentary. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  const getCommentaryBadgeColor = (type: CommentaryEntry['type']) => {
    switch (type) {
      case 'wicket':
        return "bg-red-500 text-white";
      case 'boundary':
        return "bg-blue-500 text-white";
      case 'milestone':
        return "bg-yellow-500 text-black";
      case 'strategic':
        return "bg-purple-500 text-white";
      case 'manual':
        return "bg-slate-700 text-white";
      default:
        return "";
    }
  };

  const formatTimestamp = (timestamp: Date) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <Card className="h-full flex flex-col">
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2">
          <Mic className="h-5 w-5" />
          Live Commentary
          <Badge className="ml-auto">Innings {currentInnings}</Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="flex-1 flex flex-col">
        <ScrollArea className="flex-1 pr-4 h-[400px]" ref={scrollRef}>
          <div className="space-y-4">
            {commentaryEntries.length === 0 && !isLoading ? (
              <div className="text-center py-8 text-muted-foreground">
                Commentary will appear here
              </div>
            ) : (
              commentaryEntries.map(entry => (
                <div key={entry.id} className="space-y-1 animate-fadeIn">
                  <div className="flex justify-between items-center">
                    <div className="flex items-center gap-2">
                      {entry.isAutoGenerated ? (
                        <Badge variant="outline" className="flex items-center gap-1">
                          <RotateCcw className="h-3 w-3" />
                          Auto
                        </Badge>
                      ) : (
                        <Badge variant="outline" className="flex items-center gap-1">
                          <Mic className="h-3 w-3" />
                          Manual
                        </Badge>
                      )}
                      {entry.type !== 'general' && entry.type !== 'manual' && (
                        <Badge className={getCommentaryBadgeColor(entry.type)}>
                          {entry.type.charAt(0).toUpperCase() + entry.type.slice(1)}
                        </Badge>
                      )}
                      {entry.over && (
                        <Badge variant="outline" className="text-xs">
                          Over {entry.over}
                        </Badge>
                      )}
                    </div>
                    <span className="text-xs text-muted-foreground">
                      {formatTimestamp(entry.timestamp)}
                    </span>
                  </div>
                  <p className="text-sm">{entry.text}</p>
                  <Separator className="my-2" />
                </div>
              ))
            )}
          </div>
        </ScrollArea>
        <div className="mt-4 space-y-2">
          <div className="flex gap-2">
            <Textarea 
              placeholder="Add your commentary..." 
              className="min-h-[80px]"
              value={manualEntry}
              onChange={(e) => setManualEntry(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && e.ctrlKey) {
                  handleAddManualCommentary();
                }
              }}
            />
          </div>
          <div className="flex justify-between">
            <Button
              variant="outline"
              size="sm"
              className="text-xs"
              onClick={() => setManualEntry("")}
            >
              Clear
            </Button>
            <Button 
              onClick={handleAddManualCommentary}
              disabled={isLoading || !manualEntry.trim()}
              className="gap-1"
            >
              <CornerDownLeft className="h-4 w-4" />
              Add Commentary
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}